# Generated by Django 2.1.7 on 2019-12-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0021_auto_20191206_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='grade',
            name='letter',
            field=models.CharField(max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subcode',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
